import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { balance, monthSummary, nightsBetween } from './lib/calculations';
import { useFinanceStore } from './store';
import { extraordinaryCategoryLabels, variableCategoryLabels } from './types';
import type { Expense, ExpenseKind, Platform, Reservation, VariableCategory, ExtraordinaryCategory } from './types';
import { validateExpense, validateReservation } from './lib/validation';
import './styles.css';

const PASSWORD = import.meta.env.VITE_ADMIN_PASSWORD || 'conectar-admin';
const money = (n: number) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(n);
const today = () => { const date = new Date(); const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60_000).toISOString().slice(0, 10); };

function Login({ onLogin }: { onLogin: () => void }) { const [value, setValue] = useState(''); const [error, setError] = useState(false); return <main className="grid min-h-screen place-items-center p-5"><form className="card w-full max-w-sm space-y-5" onSubmit={(e) => { e.preventDefault(); if (value === PASSWORD) onLogin(); else setError(true); }}><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Conectar Naturaleza</p><h1 className="mt-2 text-2xl font-bold">Panel financiero</h1><p className="mt-1 text-sm text-slate-500">Ingresa tu contraseña para continuar.</p></div><label className="field">Contraseña<input autoFocus type="password" value={value} onChange={(e) => { setValue(e.target.value); setError(false); }} />{error && <span className="font-normal text-red-600">Contraseña incorrecta.</span>}</label><button className="btn btn-primary w-full">Entrar</button><p className="text-xs text-slate-400">La información se guarda solo en este navegador.</p></form></main>; }

function ReservationForm({ onDone }: { onDone: () => void }) { const add = useFinanceStore((s) => s.addReservation); const [form, setForm] = useState({ checkIn: today(), checkOut: today(), passenger: '', guests: '1', platform: 'particular' as Platform, phone: '', total: '', paid: '' }); const [error, setError] = useState(''); const set = (key: string, value: string) => setForm((f) => ({ ...f, [key]: value })); const nights = nightsBetween(form.checkIn, form.checkOut); return <form className="card space-y-4" onSubmit={(e) => { e.preventDefault(); const reservation = { ...form, id: crypto.randomUUID(), guests: Number(form.guests), total: Number(form.total), paid: Number(form.paid || 0) }; const validationError = validateReservation(reservation); if (validationError) { setError(validationError); return; } add(reservation); onDone(); }}><div><h2 className="text-lg font-bold">Nueva reserva</h2><p className="text-sm text-slate-500">Las noches se calculan automáticamente.</p></div>{error && <p className="form-error">{error}</p>}<div className="grid grid-cols-2 gap-3"><label className="field">Check-in<input required type="date" value={form.checkIn} onChange={(e) => set('checkIn', e.target.value)} /></label><label className="field">Check-out<input required type="date" value={form.checkOut} onChange={(e) => set('checkOut', e.target.value)} /></label></div><p className="rounded-lg bg-emerald-50 p-2 text-sm font-bold text-emerald-800">{nights} {nights === 1 ? 'noche' : 'noches'}</p><div className="grid gap-3 sm:grid-cols-2"><label className="field">Pasajero<input required value={form.passenger} onChange={(e) => set('passenger', e.target.value)} /></label><label className="field">Huéspedes<input required min="1" type="number" value={form.guests} onChange={(e) => set('guests', e.target.value)} /></label><label className="field">Plataforma<select value={form.platform} onChange={(e) => set('platform', e.target.value as Platform)}><option value="particular">Particular</option><option value="booking">Booking</option><option value="airbnb">Airbnb</option></select></label><label className="field">WhatsApp<input placeholder="549..." value={form.phone} onChange={(e) => set('phone', e.target.value)} /></label><label className="field">Total<input required min="0" type="number" value={form.total} onChange={(e) => set('total', e.target.value)} /></label><label className="field">Pagado<input min="0" type="number" value={form.paid} onChange={(e) => set('paid', e.target.value)} /></label></div><button className="btn btn-primary w-full">Guardar reserva</button></form>; }

const variableCategories: VariableCategory[] = Object.keys(variableCategoryLabels) as VariableCategory[]; const extraordinaryCategories: ExtraordinaryCategory[] = ['extraordinary'];
function ExpenseForm({ onDone }: { onDone: () => void }) { const add = useFinanceStore((s) => s.addExpense); const [kind, setKind] = useState<ExpenseKind>('variable'); const [form, setForm] = useState({ date: today(), category: 'alquiler', description: '', amount: '' }); const [error, setError] = useState(''); const set = (key: string, value: string) => setForm((f) => ({ ...f, [key]: value })); const categories = kind === 'variable' ? variableCategories : extraordinaryCategories; return <form className="card space-y-4" onSubmit={(e) => { e.preventDefault(); const expense = { ...form, id: crypto.randomUUID(), kind, amount: Number(form.amount), category: form.category as Expense['category'] }; const validationError = validateExpense(expense); if (validationError) { setError(validationError); return; } add(expense); onDone(); }}><div><h2 className="text-lg font-bold">Nuevo gasto</h2></div>{error && <p className="form-error">{error}</p>}<div className="grid grid-cols-2 gap-3"><label className="field">Tipo<select value={kind} onChange={(e) => { const nextKind = e.target.value as ExpenseKind; setKind(nextKind); set('category', nextKind === 'variable' ? 'alquiler' : 'extraordinary'); }}><option value="variable">Costo variable</option><option value="extraordinary">Gasto extraordinario</option></select></label><label className="field">Fecha<input required type="date" value={form.date} onChange={(e) => set('date', e.target.value)} /></label><label className="field">Categoría<select value={form.category} onChange={(e) => set('category', e.target.value)}>{categories.map((item) => <option key={item} value={item}>{kind === 'variable' ? variableCategoryLabels[item as VariableCategory] : extraordinaryCategoryLabels[item as ExtraordinaryCategory]}</option>)}</select></label><label className="field">Importe<input required min="0" type="number" value={form.amount} onChange={(e) => set('amount', e.target.value)} /></label></div><label className="field">Descripción<input required maxLength={255} value={form.description} onChange={(e) => set('description', e.target.value)} /></label><button className="btn btn-primary w-full">Guardar gasto</button></form>; }

function App() { const [logged, setLogged] = useState(() => sessionStorage.getItem('admin-auth') === 'yes'); const [tab, setTab] = useState<'dashboard' | 'new' | 'history'>('dashboard'); const [month, setMonth] = useState(today().slice(0, 7)); const reservations = useFinanceStore((s) => s.reservations); const expenses = useFinanceStore((s) => s.expenses); const removeReservation = useFinanceStore((s) => s.removeReservation); const removeExpense = useFinanceStore((s) => s.removeExpense); const summary = useMemo(() => monthSummary(reservations, expenses, month), [reservations, expenses, month]); if (!logged) return <Login onLogin={() => { sessionStorage.setItem('admin-auth', 'yes'); setLogged(true); }} />; return <div className="mx-auto min-h-screen max-w-5xl px-4 pb-24 pt-6 sm:px-6"><header className="mb-7 flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Conectar Naturaleza</p><h1 className="text-2xl font-bold">Administración</h1></div><button className="btn btn-muted text-sm" onClick={() => { sessionStorage.removeItem('admin-auth'); setLogged(false); }}>Salir</button></header><nav className="mb-5 flex gap-2 overflow-x-auto"><button className={`btn ${tab === 'dashboard' ? 'btn-primary' : 'btn-muted'}`} onClick={() => setTab('dashboard')}>Resumen</button><button className={`btn ${tab === 'new' ? 'btn-primary' : 'btn-muted'}`} onClick={() => setTab('new')}>Cargar movimiento</button><button className={`btn ${tab === 'history' ? 'btn-primary' : 'btn-muted'}`} onClick={() => setTab('history')}>Historial</button></nav>{tab === 'dashboard' && <><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Dashboard mensual</h2><input className="rounded-lg border border-slate-200 bg-white p-2 text-sm" type="month" value={month} onChange={(e) => setMonth(e.target.value)} /></div><section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Ingresos" value={money(summary.income)} /><Metric label="Gastos" value={money(summary.expenses)} /><Metric label="Resultado" value={money(summary.result)} good={summary.result >= 0} /><Metric label="Huéspedes" value={String(summary.guests)} /></section><section className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Noches totales" value={String(summary.totalNights)} /><Metric label="Promedio noches" value={summary.averageNights.toFixed(1)} /><Metric label="Mediana noches" value={summary.medianNights.toFixed(1)} /><Metric label="Plataforma principal" value={summary.mostUsedPlatform} /></section></>}{tab === 'new' && <div className="grid gap-4 md:grid-cols-2"><ReservationForm onDone={() => setTab('history')} /><ExpenseForm onDone={() => setTab('history')} /></div>}{tab === 'history' && <History reservations={reservations} expenses={expenses} removeReservation={removeReservation} removeExpense={removeExpense} />}</div>; }
function Metric({ label, value, good }: { label: string; value: string; good?: boolean }) { return <div className="card"><p className="text-xs font-semibold text-slate-500">{label}</p><p className={`mt-1 truncate text-lg font-bold ${good ? 'text-emerald-700' : ''}`}>{value}</p></div>; }
function History({ reservations, expenses, removeReservation, removeExpense }: { reservations: Reservation[]; expenses: Expense[]; removeReservation: (id: string) => void; removeExpense: (id: string) => void }) { return <div className="space-y-5"><div><h2 className="mb-3 text-lg font-bold">Reservas</h2><div className="space-y-2">{reservations.length === 0 && <p className="text-sm text-slate-500">No hay reservas todavía.</p>}{reservations.map((r) => <article className="card flex items-center justify-between gap-3" key={r.id}><div><p className="font-bold">{r.passenger} · {r.platform}</p><p className="text-sm text-slate-500">{r.checkIn} → {r.checkOut} · {nightsBetween(r.checkIn, r.checkOut)} noches · {r.guests} huéspedes</p><p className="text-sm">{money(r.total)} · saldo {money(balance(r.total, r.paid))} {r.phone && <a className="ml-2 text-emerald-700 underline" href={`https://wa.me/${r.phone.replace(/\D/g, '')}`} target="_blank" rel="noreferrer">WhatsApp</a>}</p></div><button className="text-xs text-red-600" onClick={() => removeReservation(r.id)}>Eliminar</button></article>)}</div></div><div><h2 className="mb-3 text-lg font-bold">Gastos</h2><div className="space-y-2">{expenses.length === 0 && <p className="text-sm text-slate-500">No hay gastos todavía.</p>}{expenses.map((e) => <article className="card flex items-center justify-between gap-3" key={e.id}><div><p className="font-bold">{e.description}</p><p className="text-sm text-slate-500">{e.date} · {e.kind} · {e.category}</p><p className="text-sm">{money(e.amount)}</p></div><button className="text-xs text-red-600" onClick={() => removeExpense(e.id)}>Eliminar</button></article>)}</div></div></div>; }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
